Repository 42-Spring-Study/Spring, pull requests merged in 2024-04, with the labels that each got.

#36 Lec1 스프링입문 실습코드
  src/seongtki/hello-spring/.DS_Store
  src/seongtki/hello-spring/.gitignore
  src/seongtki/hello-spring/build.gradle
  src/seongtki/hello-spring/gradle/wrapper/gradle-wrapper.jar
  src/seongtki/hello-spring/gradle/wrapper/gradle-wrapper.properties
  src/seongtki/hello-spring/gradlew
  src/seongtki/hello-spring/gradlew.bat
  src/seongtki/hello-spring/settings.gradle
  src/seongtki/hello-spring/src/main/java/hello/HelloSpringApplication.java
  src/seongtki/hello-spring/src/main/java/hello/configuration/SpringConfig.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/aop/TimeTraceAop.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/controller/HelloController.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/controller/HomeController.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/controller/MemberController.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/controller/MemberForm.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/domain/Member.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/JdbcMemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/JdbcTemplateMemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/JpaMemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/MemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/MemoryMemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/repository/SpringDataJpaMemberRepository.java
  src/seongtki/hello-spring/src/main/java/hello/hellospring/service/MemberService.java
  src/seongtki/hello-spring/src/main/resources/application.properties
  src/seongtki/hello-spring/src/main/resources/static/hello-static.html
  src/seongtki/hello-spring/src/main/resources/static/index.html
  src/seongtki/hello-spring/src/main/resources/templates/hello-template.html
  src/seongtki/hello-spring/src/main/resources/templates/hello.html
  src/seongtki/hello-spring/src/main/resources/templates/home.html
  src/seongtki/hello-spring/src/main/resources/templates/members/createMemberForm.html
  src/seongtki/hello-spring/src/main/resources/templates/members/memberList.html
  src/seongtki/hello-spring/src/test/java/hello/hellospring/HelloSpringApplicationTests.java
  src/seongtki/hello-spring/src/test/java/hello/hellospring/repository/MemoryMemberRepositoryTest.java
  src/seongtki/hello-spring/src/test/java/hello/hellospring/service/MemberServiceIntegrationTest.java
  src/seongtki/hello-spring/src/test/java/hello/hellospring/service/MemberServiceTest.java
Labels: practice

#38 servlet test
  src/seongtki/servlet-mvc/.idea/.gitignore
  src/seongtki/servlet-mvc/.idea/compiler.xml
  src/seongtki/servlet-mvc/.idea/libraries/lib.xml
  src/seongtki/servlet-mvc/.idea/misc.xml
  src/seongtki/servlet-mvc/.idea/modules.xml
  src/seongtki/servlet-mvc/.idea/vcs.xml
  src/seongtki/servlet-mvc/servlet-mvc.iml
  src/seongtki/servlet-mvc/src/main/java/WebServer.java
  src/seongtki/servlet-mvc/src/main/java/basic/HelloData.java
  src/seongtki/servlet-mvc/src/main/java/basic/HelloServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/request/RequestBodyJsonServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/request/RequestBodyStringServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/request/RequestHeaderServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/request/RequestParamServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/response/ResponseHeaderServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/response/ResponseHtmlServlet.java
  src/seongtki/servlet-mvc/src/main/java/basic/response/ResponseJsonServlet.java
  src/seongtki/servlet-mvc/web/WEB-INF/lib/annotations-api.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/assertj-core-3.24.2.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/ecj-4.6.3.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/jackson-annotations-2.17.0.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/jackson-core-2.17.0.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/jackson-databind-2.17.0.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/jstl-1.2.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/junit-4.13.2.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/junit-jupiter-api-5.8.1.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/junit-platform-commons-1.8.1.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/lombok-1.18.32.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/snakeyaml-1.28.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/spring-context-6.1.5.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/spring-core-6.1.5.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/spring-web-6.1.5.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/tomcat-dbcp.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/tomcat-embed-core.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/tomcat-embed-el.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/tomcat-embed-jasper.jar
  src/seongtki/servlet-mvc/web/WEB-INF/lib/tomcat-embed-websocket.jar
  src/seongtki/servlet-mvc/web/WEB-INF/views/members.jsp
  src/seongtki/servlet-mvc/web/WEB-INF/views/new-form.jsp
  src/seongtki/servlet-mvc/web/WEB-INF/views/save-result.jsp
  src/seongtki/servlet-mvc/web/WEB-INF/web.xml
  src/seongtki/servlet-mvc/web/basic.html
  src/seongtki/servlet-mvc/web/basic/hello-form.html
  src/seongtki/servlet-mvc/web/index.html
  src/seongtki/servlet-mvc/web/index.jsp
  src/seongtki/servlet-mvc/web/jsp/members.jsp
  src/seongtki/servlet-mvc/web/jsp/members/new-form.jsp
  src/seongtki/servlet-mvc/web/jsp/members/save.jsp
Labels: practice

#42 servlet MVC 적용, 개선
  src/seongtki/servlet-mvc/src/main/java/business/domain/member/Member.java
  src/seongtki/servlet-mvc/src/main/java/business/domain/member/MemberRepository.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/ModelView.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/MyView.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v1/ControllerV1.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v1/FrontControllerServletV1.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v1/controller/MemberFormControllerV1.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v1/controller/MemberListControllerV1.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v1/controller/MemberSaveControllerV1.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v2/ControllerV2.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v2/FrontControllerServletV2.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v2/controller/MemberFormControllerV2.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v2/controller/MemberListControllerV2.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v2/controller/MemberSaveControllerV2.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v3/ControllerV3.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v3/FrontControllerServletV3.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v3/controller/MemberFormControllerV3.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v3/controller/MemberListControllerV3.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v3/controller/MemberSaveControllerV3.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v4/ControllerV4.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v4/FrontControllerServletV4.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v4/controller/MemberFormControllerV4.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v4/controller/MemberListControllerV4.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v4/controller/MemberSaveControllerV4.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v5/FrontControllerServletV5.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v5/MyHandlerAdapter.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v5/adapter/ControllerV3HandlerAdapter.java
  src/seongtki/servlet-mvc/src/main/java/web/frontcontroller/v5/adapter/ControllerV4HandlerAdapter.java
  src/seongtki/servlet-mvc/src/main/java/web/servlet/MemberFormServlet.java
  src/seongtki/servlet-mvc/src/main/java/web/servlet/MemberListServlet.java
  src/seongtki/servlet-mvc/src/main/java/web/servlet/MemberSaveServlet.java
  src/seongtki/servlet-mvc/src/main/java/web/servletmvc/MvcMemberFormServlet.java
  src/seongtki/servlet-mvc/src/main/java/web/servletmvc/MvcMemberListServlet.java
  src/seongtki/servlet-mvc/src/main/java/web/servletmvc/MvcMemberSaveServlet.java
  src/seongtki/servlet-mvc/web/jsp/members/save.jsp
Labels: practice

#43 spring mvc (구조기반코드)
  src/seongtki/spring-mvc/.gitignore
  src/seongtki/spring-mvc/build.gradle
  src/seongtki/spring-mvc/gradle/wrapper/gradle-wrapper.jar
  src/seongtki/spring-mvc/gradle/wrapper/gradle-wrapper.properties
  src/seongtki/spring-mvc/gradlew
  src/seongtki/spring-mvc/gradlew.bat
  src/seongtki/spring-mvc/settings.gradle
  src/seongtki/spring-mvc/src/main/java/me/staek/SpringMvcApplication.java
  src/seongtki/spring-mvc/src/main/java/me/staek/business/domain/member/Member.java
  src/seongtki/spring-mvc/src/main/java/me/staek/business/domain/member/MemberRepository.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/old/MyHttpRequestHandler.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/old/OldController.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/v1/SpringMemberFormControllerV1.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/v1/SpringMemberListControllerV1.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/v1/SpringMemberSaveControllerV1.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/v2/SpringMemberControllerV2.java
  src/seongtki/spring-mvc/src/main/java/me/staek/web/v3/SpringMemberControllerV3.java
  src/seongtki/spring-mvc/src/main/resources/application.properties
  src/seongtki/spring-mvc/src/main/webapp/WEB-INF/views/members.jsp
  src/seongtki/spring-mvc/src/main/webapp/WEB-INF/views/new-form.jsp
  src/seongtki/spring-mvc/src/main/webapp/WEB-INF/views/save-result.jsp
  src/seongtki/spring-mvc/src/main/webapp/basic.html
  src/seongtki/spring-mvc/src/main/webapp/basic/hello-form.html
  src/seongtki/spring-mvc/src/main/webapp/index.html
  src/seongtki/spring-mvc/src/test/java/me/staek/springmvc/SpringMvcApplicationTests.java
Labels: practice

#3 [Lec2/Sec05] 싱글톤 컨테이너
  02_스프링핵심원리-기본편/01_객체지향설계와스프링/samin.md
  02_스프링핵심원리-기본편/02_스프링핵심원리이해1-예제/samin.md
  02_스프링핵심원리-기본편/03_스프링핵심원리이해2-객체지향원리적용/samin.md
  02_스프링핵심원리-기본편/04_스프링컨테이너와스프링빈/samin.md
  02_스프링핵심원리-기본편/05_싱글톤컨테이너/junmkang.md
  02_스프링핵심원리-기본편/05_싱글톤컨테이너/samin.md
  02_스프링핵심원리-기본편/05_싱글톤컨테이너/seongtki.md
  02_스프링핵심원리-기본편/05_싱글톤컨테이너/soylee.md
  02_스프링핵심원리-기본편/img/junmkang_214.png
  02_스프링핵심원리-기본편/img/junmkang_215.png
Labels: documentation, Lec2-Core1

#16 [Lec2/Sec06] 컴포넌트 스캔
  02_스프링핵심원리-기본편/06_컴포넌트스캔/junmkang.md
  02_스프링핵심원리-기본편/06_컴포넌트스캔/samin.md
  02_스프링핵심원리-기본편/06_컴포넌트스캔/seongtki.md
  02_스프링핵심원리-기본편/06_컴포넌트스캔/soylee.md
  02_스프링핵심원리-기본편/img/seongtki_210.png
  02_스프링핵심원리-기본편/img/seongtki_211.png
  02_스프링핵심원리-기본편/img/seongtki_212.png
  02_스프링핵심원리-기본편/img/seongtki_213.png
Labels: documentation, Lec2-Core1

#28 [Lec3/Sec01] 인터넷 네트워크
  03_모든개발자를위한-HTTP웹기본지식/01_인터넷네트워크/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_101.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_102.png
Labels: documentation, Lec3-HTTP

#17 [Lec2/Sec08] 빈생명주기 콜백
  02_스프링핵심원리-기본편/08_빈생명주기콜백/junmkang.md
  02_스프링핵심원리-기본편/08_빈생명주기콜백/samin.md
  02_스프링핵심원리-기본편/08_빈생명주기콜백/seongtki.md
  02_스프링핵심원리-기본편/08_빈생명주기콜백/soylee.md
  02_스프링핵심원리-기본편/img/seongtki_214.png
Labels: documentation, Lec2-Core1

#20 [Lec3/Sec06] HTTP상태코드
  03_모든개발자를위한-HTTP웹기본지식/06_HTTP상태코드/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/06_HTTP상태코드/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_306.png
Labels: documentation, Lec3-HTTP

#18 [Lec2/Sec09] 빈 스코프
  02_스프링핵심원리-기본편/09_빈스코프/junmkang.md
  02_스프링핵심원리-기본편/09_빈스코프/samin.md
  02_스프링핵심원리-기본편/09_빈스코프/seongtki.md
  02_스프링핵심원리-기본편/img/junmkang_220.png
  02_스프링핵심원리-기본편/img/junmkang_221.png
  02_스프링핵심원리-기본편/img/junmkang_222.png
  02_스프링핵심원리-기본편/img/junmkang_223.png
  02_스프링핵심원리-기본편/img/junmkang_224.png
Labels: documentation, Lec2-Core1

#19 [Lec2/Sec07] 의존관계 자동 주입
  02_스프링핵심원리-기본편/07_의존관계자동주입/junmkang.md
  02_스프링핵심원리-기본편/07_의존관계자동주입/samin.md
  02_스프링핵심원리-기본편/07_의존관계자동주입/seongtki.md
  02_스프링핵심원리-기본편/07_의존관계자동주입/soylee.md
  02_스프링핵심원리-기본편/img/seongtki_215.png
Labels: documentation, Lec2-Core1

#21 [Lec3/Sec04] HTTP메서드
  03_모든개발자를위한-HTTP웹기본지식/04_HTTP메서드/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/04_HTTP메서드/soylee.md
  03_모든개발자를위한-HTTP웹기본지식/04_HTTP메서드/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/04_HTTP메서드/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_305.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_301.png
Labels: documentation, Lec3-HTTP

#27 [Lec3/Sec02] uri와 웹 브라우저 요청 흐름
  03_모든개발자를위한-HTTP웹기본지식/02_URI와웹브라우저요청흐름/soylee.md
  03_모든개발자를위한-HTTP웹기본지식/img/soylee_201.png
  03_모든개발자를위한-HTTP웹기본지식/02_URI와웹브라우저요청흐름/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/02_URI와웹브라우저요청흐름/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_301.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_302.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_303.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_306.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_307.png
Labels: documentation, Lec3-HTTP

#22 [Lec3/Sec05] HTTP메서드 활용
  03_모든개발자를위한-HTTP웹기본지식/05_HTTP메서드활용/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/05_HTTP메서드활용/soylee.md
  03_모든개발자를위한-HTTP웹기본지식/05_HTTP메서드활용/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/junmkang.md
Labels: documentation, Lec3-HTTP

#26 [Lec3/Sec08] HTTP헤더2-캐시와조건부요청
  03_모든개발자를위한-HTTP웹기본지식/08_HTTP헤더2-캐시와조건부요청/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/08_HTTP헤더2-캐시와조건부요청/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_308.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_309.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_304.png
Labels: documentation, Lec3-HTTP

#23 [Lec3/Sec03] HTTP기본
  03_모든개발자를위한-HTTP웹기본지식/03_HTTP기본/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/03_HTTP기본/soylee.md
  03_모든개발자를위한-HTTP웹기본지식/03_HTTP기본/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/03_HTTP기본/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_304.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_302.png
Labels: documentation, Lec3-HTTP

#25 [Lec3/Sec07] HTTP헤더1-일반헤더
  03_모든개발자를위한-HTTP웹기본지식/07_HTTP헤더1-일반헤더/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/07_HTTP헤더1-일반헤더/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_307.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_303.png
Labels: documentation, Lec3-HTTP

#46 한글폴더 복제문제
  03_모든개발자를위한-HTTP웹기본지식/01_인터넷네트워크/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/02_URI와웹브라우저요청흐름/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/02_URI와웹브라우저요청흐름/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/03_HTTP기본/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/04_HTTP메서드/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/06_HTTP상태코드/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/06_HTTP상태코드/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/07_HTTP헤더1-일반헤더/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/07_HTTP헤더1-일반헤더/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/08_HTTP헤더2-캐시와조건부요청/junmkang.md
  03_모든개발자를위한-HTTP웹기본지식/08_HTTP헤더2-캐시와조건부요청/seongtki.md
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_101.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_102.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_301.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_302.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_303.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_304.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_305.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_306.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_307.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_308.png
  03_모든개발자를위한-HTTP웹기본지식/img/junmkang_309.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_301.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_302.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_303.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_304.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_306.png
  03_모든개발자를위한-HTTP웹기본지식/img/seongtki_307.png
  03_모든개발자를위한-HTTP웹기본지식/junmkang.md
Labels: bug
